- app/views/discussions/reloadCategories.volt
- app/views/partials/top-menu.volt
> CSS bug with dropdown in Firefox

- app/models/Categories.php
- scripts/random-entries.php
> Fix scripts/random-entries.php

- app/views/partials/list-posts.volt
line 100 -- align="center", makes it look much more professional.
> line 100 -- align="center"

- composer.json
@andresgutierrez Enable please https://github.com/phalcon/forum/issues url
> Amended Composer config [ci-skip]

- .travis.yml
See https://github.com/composer/composer/issues/1314#issuecomment-10266196
> Try to fix travis build

- app/config/nginx.example.conf
- app/views/discussions/view.volt
> Inroduced structured data markup

- app/controllers/SessionController.php
- app/controllers/UsersController.php
- app/library/Github/Users.php
> Changed github authentication to login vs the auth token

- .gitignore
- app/config/config.example.php
- app/library/Utils/Backup.php
- composer.json
> Fixed Database Backup util

- .travis.yml
- README.md
- app/config/env.php
- app/library/Utils/Security.php
- composer.json
- tests/unit/Utils/SecurityTest.php
- tests/unit/Utils/SlugTest.php
> Introduced Phosphorum\Utils\Security (prefixed version)

- app/controllers/UsersController.php
- app/library/Mvc/Controllers/TokenTrait.php
- app/views/users/settings.volt
> Fixed CSRF in in user settings form

- app/controllers/ControllerBase.php
- app/controllers/DiscussionsController.php
- app/views/discussions/create.volt
> Fixed CSRF check by creating post 

- app/controllers/DiscussionsController.php
- app/views/discussions/edit.volt
> Fixed CSRF check by editing post

- app/controllers/DiscussionsController.php
- app/controllers/PollsController.php
- app/controllers/RepliesController.php
- app/library/Mvc/Controllers/TokenTrait.php
- app/views/discussions/view.volt
> Fixed CSRF check for subscription, voting, etc

- app/library/Search/Indexer.php
See https://github.com/phalcon/forum/issues/249
> Issue 249 fix: removing redundancy in Search/Indexer.php

- composer.json
> Fix post-root-package-install script

- .travis.yml
- app/controllers/ControllerBase.php
- app/controllers/DiscussionsController.php
> Properly escaping user input/output

- app/config/env.php
- app/helpers.php
- app/views/partials/list-posts-short.volt
- app/views/partials/list-posts.volt
- public/css/style.css
* Added some path helpers
* Improved sticked posts view thanks to @oscarmolinadev (+ fixed indents)
> Added some path helpers

- scripts/clear-cache.php
This is a script for clearing all the cache files of Phosphorum. I used it very often during my development, so contribute it to phosphorum.
> Clear cache script

- app/config/routes.php
- app/controller/CategoriesController.php
- app/controller/SessionController.php
- app/model/Users.php
- app/views/partials/top-menu.volt
- schemas/upgrade-to-3.3.sql
Added new role - administrator.
Addition of categories by the administrator is added.
> Creating new category added.

- app/controller/RepliesController.php
Hello!
Changed decrease user's reputation when he clicks dislike. On forum's activity list doesn't have any notification about it.
Thanks
> Changed decrease someone karma when he clicks dislike on reply

- app/model/Services/Service/Activities.php
- app/model/Services/Service/Posts.php
Hello!
Fixed PHQL queries.
Thanks
> Fixed PHQL queries

- app/provider/Markdown/Plugins/UnderscoredUrlsExtension.php
- tests/acceptance/PostLinkTestCest.php
- tests/functional/CorrectConvertUriCest.php
Hello!
* Link to issue: #239
Fixed incorrect url in posts
Thanks
> Fixed url in posts

- .gitignore
- app/library/Discord/DiscordComponent.php
- app/task/Discord.php
- app/task/Searchengine.php
Fixes: https://github.com/phalcon/forum/issues/400
> Fixed discord task

- app/controller/UtilsController.php
Hello!
Fix incorrect show special symbols in post's preview.
Thanks
> Fix special symbols in preview

- app/provider/Markdown/Plugins/BlockQuoteExtension.php
- tests/acceptance/BlockQuoteTestCest.php
Hello!
* Link to issue: - 
Fix to correct display text in block-quote.
Thanks
> Fix block-quote text block

- app/library/Markdown/Markdown.php
- tests/acceptance/BlockQuoteTestCest.php
- tests/acceptance/InjectionTestCest.php
- tests/acceptance/PostAndReplyTestCest.php
- tests/acceptance/SpecialSymbolTestCest.php
Hello!
Added protection to prevent xss injection.
Thanks
> Add prevent injection

- .travis.yml
- app/library/Markdown/Markdown.php
- app/views/help/markdown.volt
- tests/acceptance/DelTagTestCest.php
- tests/acceptance/InsTagTestCest.php
- tests/acceptance/SpecialSymbolTestCest.php
Hello!
Added support ins and del tags to new markdown
Thanks
> Added support ins and del tags to new markdown

- app/library/Version.php
- tests/console/HelpCept.php
- tests/console/VersionCept.php
Hello!
* Type: new version
Bump version
Thanks
> Update forum version to 3.4.1

- app/views/partials/post/reply-popup.volt
- public/js/forum.js
Hello!
Added support highlight in preview
Thanks
> Added highlight in preview

- .travis.yml
Hello!
Fixed NotificationCestTest
Thanks
> Change travis

- app/listener/PostListener.php
- app/model/CacheableModel.php
- app/model/Posts.php
- app/model/PostsHistory.php
- app/model/PostsViews.php
- app/model/TopicTracking.php
- config/database.php
- tests/_support/Helper/User.php
- tests/acceptance.suite.yml
- tests/acceptance/PostListenerTestCest.php
Hello!
* Type: bug fix & new feature
Added postListener
Thanks
> Add post listener

- app/task/Cache.php
- tests/_data/assets/script.js
- tests/_data/assets/style.css
- tests/console/ClearCacheCept.php
Hello!
Improve clear cache task. Add removing assets collections files.
Thanks
> Add removing assets collections files

- app/listener/PostRepliesListener.php
- app/model/PostsReplies.php
Hello!
* Type: code quality
**In raising this pull request, I confirm the following (please check boxes):**
Add postReplies listener and refactor postReplies model
Thanks
> Add postReplies listener and refactor postReplies model

- .travis.yml
Hello!
* Type: 
* Link to issue: #450
Remove from failure php7.2
Thanks
> Remove from failure php7.2

- app/controller/CategoriesController.php
- tests/acceptance/CategoryPaginationCest.php
Hello!
* Link to issue: #371
Add pagination when category was selected
Thanks
> Add pagination when category was selected

- app/model/PostsReplies.php
Hello!
* Link to issue: - 
Fix methods `getHumanCreatedAt` and `getHumanEditedAt`.
Thanks
> Fix post_reply model create and change time

- CHANGELOG-2.md
- CHANGELOG-3.md
- CHANGELOG.md
Hello!
* Type: documentation
* Link to issue: #58
Add changelog
Thanks
> Add changelog

- CHANGELOG.md
- app/listener/UsersListener.php
- app/model/Users.php
Hello!
* Type: refactor
* Link to issue: #465
Add `UsersListener` to `Users` model
Thanks
> Add UsersListener

- CHANGELOG-3.5.md
- CHANGELOG.md
Hello!
* Type: documentation
Add ChangeLog-3.5.x
Thanks
> Add ChangeLog-3.5.x

- CHANGELOG-3.5.md
Hello!
* Type: documentation
Add information about 3.5.0 release to changelog
Thanks
> Add information about 3.5.0 release to changelog

- CHANGELOG-4.0.md
- CHANGELOG.md
Hello!
* Type: documentation
Add Changelog-4.0
Thanks
> Add Changelog-4.0

- app/controller/ControllerBase.php
- app/views/index.volt
> Revert "Try to use collection"

- app/controller/ControllerBase.php
- app/library/Assets/AssetsManagerExtended.php
- app/views/index.volt
> Revert "Try to use 2"

- app/controller/ControllerBase.php
- app/library/Assets/AssetsManagerExtended.php
- app/library/Exception/RuntimeException.php
- app/services/Controller/AssetsService.php
- composer.json
Hello!
* Type: code quality
Refactor generating assets collection and move calling it from `onConstruct` to `initialize`
Thanks
> Refactor assets collection

- app/controller/ControllerBase.php
- app/library/Assets/AssetsManagerExtended.php
- app/library/Exception/InvalidParameterException.php
- app/library/Exception/RuntimeException.php
- app/services/Controller/AssetsService.php
Hello!
* Type: code quality
Refactor generating assets collection and move calling it from `onConstruct` to `initialize`
Thanks
> 4.0.refactor assets

- app/controller/ControllerBase.php
- app/views/index.volt
> Try to use 3

- app/controller/ControllerBase.php
- app/views/index.volt
> Revert "Try to use 3"

- .travis.yml
- app/controller/ControllerBase.php
- app/library/Assets/AssetsManagerExtended.php
- app/views/index.volt
Hello!
* Type: try
**In raising this pull request, I confirm the following (please check boxes):**
Thanks
> Try to use 4

- .env.example
- CHANGELOG.md
- app/library/Discord/DiscordComponent.php
- app/library/Mail/SendNotifications.php
- app/listener/PostListener.php
- app/listener/PostRepliesListener.php
- app/services/QueueService.php
- app/task/Discord.php
Hello!
* Type: changes
* Link to issue:
Add service and method for creating queue name
Thanks
> Add service and method for creating queue name

- CHANGELOG-3.md
- CHANGELOG.md
- app/library/Assets/Filters/NoneFilter.php
- app/services/Controller/AssetsService.php
Hello!
* Type:new feature & documentation
Add nonFilter and change Changelog
Thanks
> Addув NoneFilter and update change log

- CHANGELOG-3.md
- app/library/Console/AbstractTask.php
- app/library/System/Platform.php
- app/provider/Registry/ServiceProvider.php
- app/provider/consoleOutput/ServiceProvider.php
- app/services/Controller/AssetsService.php
- app/task/Cache.php
- app/task/Commands.php
- app/task/Install.php
- app/task/Searchengine.php
- app/task/Seeder.php
- app/task/Version.php
- config/providers.php
- tests/console/NotificationCest.php
Hello!
* Type: new feature & code quality
Added `Install` CLI controller and `checkDirs` action.
Refactor `Cache`, `Commands`, `Help`, `Searchengine`, `Seeder`, `Version` CLI controllers.
Thanks
> Add install task

- tests/_support/Helper/User.php
- tests/console/NotificationCest.php
Hello!
* Link to issue: #480
fix NotificationCest. Add method that generate valid email.
Thanks
> fix NotificationCest

- CHANGELOG-3.md
- app/library/Utils/Backup.php
- composer.json
- composer.lock
Hello!
* Type: changing
* Link to issue: #531
Using `srmklive/flysystem-dropbox-v2` of version v1.0.7 instead `league/flysystem-dropbox` 
Thanks
> Change dropbox client

- app/library/Version.php
- tests/console/HelpCept.php
- tests/console/VersionCept.php
Hello!
* Type: info about new version
Bump new version 3.6.0
Thanks
> Bump version 3.6.0 [ci skip]

- public/500.html
- public/503.html
> Revert "mail changed domain"
