- app/views/partials/top-menu.volt
The search dropdown now makes use of [Bootstrap's input-group component](http://getbootstrap.com/components/#input-groups).
Here's a before and after (in Chrome): http://imgur.com/ufRCbyf
> The search dropdown now makes use of Bootstrap's input-group component

- app/config/services.php
- app/controllers/DiscussionsController.php
- app/library/Markdown/UnderscoredUrlsExtension.php
- app/models/Posts.php
- app/models/TopicTracking.php
- composer.json
- tests/functional/CorrectConvertUrlCept.php
In accordance with [rfc1738][1]:
> Thus, only alphanumerics, the special characters "$-_.+!\*'(),",
> and reserved characters used for their reserved purposes **may be used** unencoded within a URL.
**may be** used, but not **must be** used unencoded.
I decoded `_` to safe equivalent `%5`.
For more detail see: https://github.com/kzykhys/Ciconia/issues/42
[1]: http://www.rfc-editor.org/rfc/rfc1738.txt
> Fixed #85 issue

- app/library/Utils/Security.php
Fixed `Phosphorum\Utils\Security::checkPrefixedToken` to prevent possible timing
attack.
> Fixed Security::checkPrefixedToken

- .env.example
A trivial change to the `.env.example` so the default matches the expected route for the system to reduce confusion when configuring the `callback_url` with github
> /github/oauth/access_token is not a valid route the system uses /login/oauth/access_token/

- public/css/style.css
When in portrait on an iPad the tab navigation was overlapped by the fixed header.
> Add media queries so that the forum tab navigation isn't lost on ipads in portrait mode

- app/model/Karma.php
Hello!
Changed `Adding a reply on someone else's post` to 15 in `app/model/Karma.php`. In description of reputation on forum this value is 15.
Thanks
> Fixed value Adding a reply on someone elses post in Karma.php

- app/controller/DiscussionsController.php
Hello!
`app/controller/DiscussionsController.php` - changed counting reputation when post was deleting. When user deleted own post, his reputations wasn't changing. Decrease karma started when ID user's post don't equal ID current user.
Thanks
> Changed counting karma when post was deleting

- app/controller/RepliesController.php
Hello!
Changed added reputation point when reply is 'accepted answer'. The forum's activity list has `Getting an own reply as 'accepted answer' by someone else` = `50 + abs(user_karma - your_karma) / 1000`.
Thanks
> Changed count reputation when reply is accept answer

- app/controller/RepliesController.php
Hello!
When someone was deleting own reply, post's owner karma decreased. Activity list on forum doesn't have any notification users about it.
Thanks
> Changed decrease reputation when someone deleted own reply

- app/provider/Markdown/Plugins/SpecSymbolExtension.php
- app/provider/Markdown/ServiceProvider.php
- app/views/discussions/view.volt
- tests/acceptance/SpecialSymbolTestCest.php
Hello!
* Link to issue: #40
Fix special symbols in post text. `&#039;` instead of `'`
Thanks
> Fix spec symbol in post

- app/views/partials/post/reply.volt
- tests/acceptance/PostAndReplyTestCest.php
Hello!
Fix spec symbols in replies. Escaping symbols makes in ciconia plugin
Thanks
> Fix spec symbols in replies

- app/provider/Markdown/Plugins/SpecSymbolExtension.php
- app/views/help/markdown.volt
- public/css/editor.css
- public/css/style.css
- tests/acceptance/SpecialSymbolTestCest.php
Hello!
* Link to issue: #51
Added support `ins` and `del` tags to posts text
Thanks
> Add support del and ins tags to post

- app/controller/DiscussionsController.php
- tests/acceptance/TitleTestCest.php
Hello!
* Type: bug fix 
Fix title. Deleted additional escaping special symbols. 
Thanks
> Fixed double escaped title

- app/library/Mail/SendSpool.php
- app/model/Posts.php
- app/model/PostsReplies.php
- config/session.php
- tests/console/NotificationsCest.php
* Don't use session if session not started
* Fixed memcached session config
* Improved notifications settings
>  Don't use session if session not started

- app/controller/DiscussionsController.php
Hello!
* Link to issue:
Prevent to add post's view after creating of post
Thanks
> Prevent to add amount of post view of post author

- app/library/Markdown/Markdown.php
- tests/functional/LinkToMentionCest.php
Hello!
Fix incorrect link to user name with dash
Thanks
> Fix username with dash

- public/js/forum.js
Hello!
Delete call of deprecated function prettyPrint
Thanks
> Delete deprecated function

- app/controller/DiscussionsController.php
Hello!
To prevent appear 500x error, when send empty reply message
Thanks
> Checking empty message in reply

- app/model/PostsReplies.php
Hello!
To prevent appear 500x, when queue adapter doesn't work
Thanks
> Prevent error when queue does not work

- tests/console/ClearCacheCept.php
Hello!
**In raising this pull request, I confirm the following (please check boxes):**
Add checking collection files after copy
Thanks
> Improve clearCacheCest

- CHANGELOG.md
- app/controller/CategoriesController.php
- app/controller/DiscussionsController.php
- app/views/partials/list-posts.volt
- tests/acceptance/RepliesCounterCest.php
Hello!
* Link to issue: #50
Change replies counter. Amount include posts's owner and visitors' replies.
Thanks
> Change replies counter

- CHANGELOG.md
- config/config.php
Hello!
* Link to issue: #473
Change default log path for error in config.php
Thanks
> Change default log path for error in config.php

- CHANGELOG-3.md
- app/library/Exception/InvalidParameterException.php
- app/library/Github/OAuth.php
- app/library/Github/Users.php
- app/library/Version.php
Hello!
* Link to issue: #472
Use `GuzzleHttp\Client` in favr of `Guzzle\Http\Client`.
Thanks
> Use GuzzleHttp\Client in favr of Guzzle\Http\Client
